version: "3.9"

services:
  api:
    build: ./api
    environment:
      PORT: 3000
      DATABASE_URL: postgresql://app:change-me@your-rds-endpoint:5432/app
      BASIC_AUTH_USER: admin
      BASIC_AUTH_PASS: admin
    ports:
      - "3000:3000"

  web:
    build: ./web
    environment:
      BASIC_AUTH_USER: admin
      BASIC_AUTH_PASS: admin
    ports:
      - "8080:80"
