version: "3.9"
services:
db:
image: postgres:16
environment:
POSTGRES_DB: app
POSTGRES_USER: app
POSTGRES_PASSWORD: app
ports: ["5432:5432"]
api:
build: ./api
environment:
PORT: 3000
BASIC_AUTH_USER: admin
BASIC_AUTH_PASS: admin
ports: ["3000:3000"]
depends_on: [db]
web:
build: ./web
environment:
BASIC_AUTH_USER: admin
BASIC_AUTH_PASS: admin
ports: ["8080:80"]

