name: build-and-deploy
on:
push:
branches: [ main ]


env:
AWS_REGION: us-east-1
PROJECT: sample-app


jobs:
build-and-push:
runs-on: ubuntu-latest
permissions:
id-token: write
contents: read
steps:
- uses: actions/checkout@v4
- uses: aws-actions/configure-aws-credentials@v4
with:
role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
aws-region: ${{ env.AWS_REGION }}
- uses: aws-actions/amazon-ecr-login@v2
- name: Build & push API
uses: docker/build-push-action@v6
with:
context: ./api
push: true
tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.PROJECT }}-api:latest
- name: Build & push Web
uses: docker/build-push-action@v6
with:
context: ./web
push: true
tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.PROJECT }}-web:latest
- name: Update ECS services
run: |
aws ecs update-service --cluster ${PROJECT}-cluster --service ${PROJECT}-api --force-new-deployment
aws ecs update-service --cluster ${PROJECT}-cluster --service ${PROJECT}-web --force-new-deployment
